name: Feature Request Yaml
description: File a feature request or task
title: "[FTR]: "
labels: ["triage"]
projects: ["Team Engineering Project"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: A clear and concise description of the problem or use case
      placeholder: e.g. It is difficult to get and use one of the previous versions of data (already overwritten by updated data) in your ML experiment.  
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Requested solution
      description: A clear and concise description of what you want to happen or achieve
      placeholder: e.g. I want to get previous (overwritten) data version after indicating a commit SHA 
    validations:
      required: true
  - type: textarea
    id: proposed_approach
    attributes:
      label: Proposed implementation approach
      description: A clear and concise description of how want to implement your solution
      placeholder:  
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additonal context
      description: Add any other context about the problem here
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: related_issues
    attributes:
      label: Related issues
      description: use "#issue number"
    validations:
      required: false      
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria (mandatory to start implementation)
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        - [ ] Add more as needed
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done (mandatory to close an issue as completed)
      options:
        - label: All applicable Definition of Done met
          required: false  
  
