name: Pull Request Yaml Test 2
description: File a pull request
body:
  - type: markdown
    attributes:
      value: Closes [#issue] 
  - type: textarea
    id: describe_change
    attributes:
      label: Desribe the change
      description: A clear and concise description of the change
      placeholder:   
    validations:
      required: false
